### PR TITLE
close a node when the lb is worse than the incumbent

### PR DESCRIPTION
**Pull request by Wikunia**
As pointed out by @dhendryc in #17 we should not branch on a node if it's worse than the incumbent

A test case would be great :smile:

### CODE REVIEW

**Comment by matbesancon** [comment]
when a new node is generated, it inherits its initial lower bound from its parent right? In that case, the update can happen whenever a new incumbent is found: go through all nodes and close those that have a higher lower bound than the incumbent

**Comment by Wikunia** [comment]
That's already happening in `bound!` isn't it? It is called when a new incumbent is found. The issue this PR fixes is however that we close the current node if after the evaluation it has a higher lower bound than the incumbent. So the lower bound got updated due to evaluation.

**Comment by matbesancon** [comment]
oh right indeed. One way to test this would be to introduce an info callback system, a callback that the user can pass, which at every iteration receives the tree, processed node (so it has to be before closing it)

**Comment by Wikunia** [comment]
Yeah was wondering whether it makes sense to introduce a bunch of `cb_` functions like `cb_new_incumbent` which gets called when a new incumbent is called. Which should work nicely with default methods that do `nothing`.

**Comment by matbesancon** [comment]
I guess they could be regrouped in a few callbacks? If the tree is passed to the callback, one can recompute the information that's not already there (whether the node will be eliminated for example)

**Comment by Wikunia** [comment]
I suppose so but was wondering whether it's more user friendly to have several of them. One doesn't need to call Bonobo with the names of the callbacks as one would need to in other languages due to dispatch, right? I would assume that we could easily use this to apply heuristics at certain points then as an example. When we only have one call we would need to provide methods to check whether a new incumbent was set or whether some event occurred. I would have one callback which is called in every run through the optimize loop which contains all the information and then some special ones like new solution?

**Comment by matbesancon** [comment]
> I suppose so but was wondering whether it's more user friendly to have several of 

Yes I was thinking of an info / printing callback for now and adding others later

> One doesn't need to call Bonobo with the names of the callbacks as one would need to in other languages due to dispatch, right?

Not sure what you mean there?

> When we only have one call we would need to provide methods to check whether a new incumbent was set or whether some event occurred

Depending on the moment in the loop where the method is called, this can be recomputed in the callback, even though not the cleanest

**Comment by Wikunia** [comment]
I meant that in other languages one often needs to write something like `optimize(callback=my_callback)` which on my idea would result in a lot of different arguments for each callback which wouldn't be nice. In Julia however we don't have the problem which made me wonder whether having a lot of smaller callbacks is the better approach.

Agree though however that for a start a single callback is fine

**Comment by dhendryc** [comment]
> As pointed out by @dhendryc in #17 we should not branch on a node if it's worse than the incumbent
> 
> A test case would be great 😄

Thank you! I am not sure how to formally test this. I'll think about it. But I checked with my example. It did cut off nodes as expected and it also reduced the number of evaluated nodes by about a third (for that particular example anyway).

**Comment by Wikunia** [comment]
I hope the additional test reasonable for this PR

**Pull request merged**
