### PR TITLE
bugfix worse lower bound than incumbent

### PR DESCRIPTION
**Pull request by Wikunia**
Only add a new solution if it can produce better results than the current incumbent.
Also if the lower bound is worse after evaluating the node we don't want to falsely update the lower bound such that it looks like the lower bound is worse than the incumbent

### CODE REVIEW

**Comment by matbesancon** [comment]
> Only add a new solution if it can produce better results than the current incumbent.

depends, one could want to store multiple solutions as discussed another issue, but the first / last one should always be the best solution yes

**Comment by Wikunia** [comment]
Here it's more about adding a new node only if it can produce results better than the current incumbent.

**Comment by matbesancon** [comment]
alright then looks good

**Comment by matbesancon** [comment]
should we merge this?

**Pull request merged**
