### PR TITLE
Return incumbent solution

### PR DESCRIPTION
**Pull request by dhendryc**
Currently the first of the collect solutions is returned. That isn't necessarily the correct one, though.

### CODE REVIEW

**Comment by matbesancon** [comment]
ping @Wikunia

**Comment by Wikunia** [comment]
It should be due to https://github.com/Wikunia/Bonobo.jl/blob/main/src/Bonobo.jl#L291 do you have an example where this isn't the case?

**Comment by dhendryc** [comment]
Interesting... When is this called?

Yes, I have an example there that does not work. I don't know if I can create a minimal working example though.

**Comment by matbesancon** [comment]
it seems like it could not be the case in the callback for instance?

**Comment by dhendryc** [comment]
No, the `sort_solutions!` is called after we exit the loop in `optimize!` . That's fine.

But you sort with :max sense. Should that depend on the problem sense?

**Comment by Wikunia** [comment]
I sort by reverse `sense == :Max` as internally everything is for minimization problems. @matbesancon yes for callbacks one would need to call something else though I'm not sure whether it makes sense to call result in that callback.

**Comment by dhendryc** [comment]
Yes, you are right. It was an issue on our side. The callback is called before `sort_solutions!`. Fixed it!

**Pull request closed without merging**
